<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<artifactId>afirma-server-retriever-jakarta</artifactId>
	<packaging>war</packaging>
	
	<name>afirma-server-retriever-jakarta</name>
	<description>Servicio para la recuperacion de datos de servidor para Tomcat 10 y superiores</description>

	<parent>
		<groupId>es.gob.afirma</groupId>
		<artifactId>afirma-client</artifactId>
		<version>1.10</version>
	</parent>
	
	<properties>
		<java.version>11</java.version>
	</properties>
	
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
		</dependency>
		
		<dependency>
    		<groupId>es.gob.afirma</groupId>
    		<artifactId>afirma-server-retriever</artifactId>
    		<version>${clienteafirma.version}</version>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<version>6.1.0</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
		
	<build>
		<plugins>			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.2.2</version>
				<configuration>  
					<archive>  
						<addMavenDescriptor>false</addMavenDescriptor> 
					</archive> 
				</configuration>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-eclipse-plugin</artifactId>
				<version>2.10</version>
				<configuration>
					<wtpapplicationxml>true</wtpapplicationxml>
					<wtpversion>2.0</wtpversion>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
					<fork>true</fork>
					<compilerArgument>-XDignore.symbol.file</compilerArgument>
				</configuration>
			</plugin>

		</plugins>
		
		<finalName>afirma-signature-retriever</finalName>
	</build>
</project>
