
var Constants = {
		
	// IMPORTANTE: PARA PRUEBAS, USAR SIEMPRE UNA IP O NOMBRE DE DOMINIO, NUNCA 'LOCALHOST' O '127.0.0.1'
	// SI NO SE HACE ASI, AUTOFIRMA BLOQUEARA LA FIRMA POR SEGURIDAD
	
	/* DESARROLLO */
	//URL_BASE_SERVICES : "https://192.168.1.113:8443"
	URL_BASE_SERVICES : "https://appprueba:8443"
};