# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PortaFirmasUniv' do
    
    pod 'SVProgressHUD'    
    pod 'T21Log' , '~> 2.0'
    pod 'OpenSSL', '~> 1.0'

end

