/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_Attribute_H_
#define	_Attribute_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AttributeType.h"
#include "AttributeValue.h"
#include "asn_SET_OF.h"
#include "constr_SET_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Attribute */
typedef struct Attribute {
	AttributeType_t	 type;
	struct values {
		A_SET_OF(AttributeValue_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} values;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Attribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Attribute;

#ifdef __cplusplus
}
#endif

#endif	/* _Attribute_H_ */
