/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CertificateSet_H_
#define	_CertificateSet_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ANY.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CertificateSet */
typedef ANY_t	 CertificateSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateSet;
asn_struct_free_f CertificateSet_free;
asn_struct_print_f CertificateSet_print;
asn_constr_check_f CertificateSet_constraint;
ber_type_decoder_f CertificateSet_decode_ber;
der_type_encoder_f CertificateSet_encode_der;
xer_type_decoder_f CertificateSet_decode_xer;
xer_type_encoder_f CertificateSet_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateSet_H_ */
