/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_EncapsulatedSignedData_H_
#define	_EncapsulatedSignedData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ContentType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignedData;

/* EncapsulatedSignedData */
typedef struct EncapsulatedSignedData {
	ContentType_t	 oid;
	struct SignedData	*content	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncapsulatedSignedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncapsulatedSignedData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignedData.h"

#endif	/* _EncapsulatedSignedData_H_ */
