/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ESSCertIDv2_H_
#define	_ESSCertIDv2_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Hash.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlgorithmIdentifier;
struct IssuerSerial;

/* ESSCertIDv2 */
typedef struct ESSCertIDv2 {
	struct AlgorithmIdentifier	*hashAlgorithm	/* DEFAULT {algorithm id-sha256} */;
	Hash_t	 certHash;
	struct IssuerSerial	*issuerSerial	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ESSCertIDv2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ESSCertIDv2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlgorithmIdentifier.h"
#include "IssuerSerial.h"

#endif	/* _ESSCertIDv2_H_ */
