/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_Hash_H_
#define	_Hash_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Hash */
typedef OCTET_STRING_t	 Hash_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Hash;
asn_struct_free_f Hash_free;
asn_struct_print_f Hash_print;
asn_constr_check_f Hash_constraint;
ber_type_decoder_f Hash_decode_ber;
der_type_encoder_f Hash_encode_der;
xer_type_decoder_f Hash_decode_xer;
xer_type_encoder_f Hash_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Hash_H_ */
