/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 */

#include "asn_internal.h"

#include "IssuerSerial.h"

static asn_TYPE_member_t asn_MBR_IssuerSerial_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IssuerSerial, issuer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeneralNames,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"issuer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IssuerSerial, serial),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CertificateSerialNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serial"
		},
	{ ATF_POINTER, 1, offsetof(struct IssuerSerial, issuerUID),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_UniqueIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"issuerUID"
		},
};
static ber_tlv_tag_t asn_DEF_IssuerSerial_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_IssuerSerial_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* serial at 71 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 0 }, /* issuerUID at 72 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* issuer at 70 */
};
static asn_SEQUENCE_specifics_t asn_SPC_IssuerSerial_specs_1 = {
	sizeof(struct IssuerSerial),
	offsetof(struct IssuerSerial, _asn_ctx),
	asn_MAP_IssuerSerial_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IssuerSerial = {
	"IssuerSerial",
	"IssuerSerial",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IssuerSerial_tags_1,
	sizeof(asn_DEF_IssuerSerial_tags_1)
		/sizeof(asn_DEF_IssuerSerial_tags_1[0]), /* 1 */
	asn_DEF_IssuerSerial_tags_1,	/* Same as above */
	sizeof(asn_DEF_IssuerSerial_tags_1)
		/sizeof(asn_DEF_IssuerSerial_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IssuerSerial_1,
	3,	/* Elements count */
	&asn_SPC_IssuerSerial_specs_1	/* Additional specs */
};

