/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_OtherHashAlgAndValue_H_
#define	_OtherHashAlgAndValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AlgorithmIdentifier.h"
#include "OtherHashValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OtherHashAlgAndValue */
typedef struct OtherHashAlgAndValue {
	AlgorithmIdentifier_t	 hashAlgorithm;
	OtherHashValue_t	 hashValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtherHashAlgAndValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherHashAlgAndValue;

#ifdef __cplusplus
}
#endif

#endif	/* _OtherHashAlgAndValue_H_ */
