/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RevocationInfoChoices_H_
#define	_RevocationInfoChoices_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ANY.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RevocationInfoChoices */
typedef ANY_t	 RevocationInfoChoices_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevocationInfoChoices;
asn_struct_free_f RevocationInfoChoices_free;
asn_struct_print_f RevocationInfoChoices_print;
asn_constr_check_f RevocationInfoChoices_constraint;
ber_type_decoder_f RevocationInfoChoices_decode_ber;
der_type_encoder_f RevocationInfoChoices_encode_der;
xer_type_decoder_f RevocationInfoChoices_decode_xer;
xer_type_encoder_f RevocationInfoChoices_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RevocationInfoChoices_H_ */
