/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SignerIdentifier_H_
#define	_SignerIdentifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IssuerAndSerialNumber.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SignerIdentifier */
typedef IssuerAndSerialNumber_t	 SignerIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignerIdentifier;
asn_struct_free_f SignerIdentifier_free;
asn_struct_print_f SignerIdentifier_print;
asn_constr_check_f SignerIdentifier_constraint;
ber_type_decoder_f SignerIdentifier_decode_ber;
der_type_encoder_f SignerIdentifier_encode_der;
xer_type_decoder_f SignerIdentifier_decode_xer;
xer_type_encoder_f SignerIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SignerIdentifier_H_ */
