/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SigningCertificateV2_H_
#define	_SigningCertificateV2_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"
#include "SigningCertificateCommonTypes.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ESSCertIDv2;
struct PolicyInformation;

/* SigningCertificateV2 */
typedef struct SigningCertificateV2 {
	struct certs certs;
	struct policies *policies;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SigningCertificateV2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SigningCertificateV2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ESSCertIDv2.h"
#include "PolicyInformation.h"

#endif	/* _SigningCertificateV2_H_ */
