/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SigningCertificate_H_
#define	_SigningCertificate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ESSCertID;
struct PolicyInformation;

/* SigningCertificate */
typedef struct SigningCertificate {
	struct certs {
		A_SEQUENCE_OF(struct ESSCertID) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} certs;
	struct policies {
		A_SEQUENCE_OF(struct PolicyInformation) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *policies;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SigningCertificate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SigningCertificate;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ESSCertID.h"
#include "PolicyInformation.h"

#endif	/* _SigningCertificate_H_ */
