#!/bin/sh
# Cerramos el navegador Firefox para instalar correctamente los certificados
if pgrep firefox; then
pkill firefox;
fi

# Creamos los directorios necesarios para no obtener errores durante la instalacion
mkdir -p /root/.local/share/applications/
mkdir -p /root/.config/
