Imports Microsoft.Win32
Module Program
    Sub Main(args As String())
        Console.WriteLine("Se van a instalar los registros necesarios para el plugin hash")
        Dim hashFileReg As RegistryKey = Registry.ClassesRoot.CreateSubKey("*\shell\afirma.hashFile")
        hashFileReg.SetValue("", "Generar huella digital")
        hashFileReg.SetValue("Icon", args(0) + "\AutoFirma.exe")
        hashFileReg.Close()
        Dim hashFileCommandReg As RegistryKey = Registry.ClassesRoot.CreateSubKey("*\shell\afirma.hashFile\command")
        hashFileCommandReg.SetValue("", args(0) + "\AutoFirma.exe createdigest ""%1"" -gui")
        hashFileCommandReg.Close()
        Dim hashDirectory As RegistryKey = Registry.ClassesRoot.CreateSubKey("Directory\shell\afirma.hashDirectory")
        hashDirectory.SetValue("", "Generar huella digital")
        hashDirectory.SetValue("Icon", args(0) + "\AutoFirma.exe")
        hashDirectory.Close()
        Dim hashDirectoryCommand As RegistryKey = Registry.ClassesRoot.CreateSubKey("Directory\shell\afirma.hashDirectory\command")
        hashDirectoryCommand.SetValue("", args(0) + "\AutoFirma.exe createdigest ""%1"" -gui")
        hashDirectoryCommand.Close()
        Dim hash As RegistryKey = Registry.ClassesRoot.CreateSubKey(".hash\shell\afirma.hash")
        hash.SetValue("", "Comprobar huella digital")
        hash.SetValue("Icon", args(0) + "\AutoFirma.exe")
        hash.Close()
        Dim hashCommand As RegistryKey = Registry.ClassesRoot.CreateSubKey(".hash\shell\afirma.hash\command")
        hashCommand.SetValue("", args(0) + "\AutoFirma.exe checkdigest -i ""%1"" -gui")
        hashCommand.Close()
        Dim hashB64 As RegistryKey = Registry.ClassesRoot.CreateSubKey(".hashb64\shell\afirma.hasbh64")
        hashB64.SetValue("", "Comprobar huella digital")
        hashB64.SetValue("Icon", args(0) + "\AutoFirma.exe")
        hashB64.Close()
        Dim hashB64Command As RegistryKey = Registry.ClassesRoot.CreateSubKey(".hashb64\shell\afirma.hasbh64\command")
        hashB64Command.SetValue("", args(0) + "\AutoFirma.exe checkdigest -i ""%1"" -gui")
        hashB64Command.Close()
        Dim hashFiles As RegistryKey = Registry.ClassesRoot.CreateSubKey(".hashfiles\shell\afirma.hashfiles")
        hashFiles.SetValue("", "Comprobar huella digital")
        hashFiles.SetValue("Icon", args(0) + "\AutoFirma.exe")
        hashFiles.Close()
        Dim hashFilesCommand As RegistryKey = Registry.ClassesRoot.CreateSubKey(".hashfiles\shell\afirma.hashfiles\command")
        hashFilesCommand.SetValue("", args(0) + "\AutoFirma.exe checkdigest -i ""%1"" -gui")
        hashFilesCommand.Close()
		Dim hexHash As RegistryKey = Registry.ClassesRoot.CreateSubKey(".hexhash\shell\afirma.hexhash")
        hexHash.SetValue("", "Comprobar huella digital")
        hexHash.SetValue("Icon", args(0) + "\AutoFirma.exe")
        hexHash.Close()
        Dim hexHashCommand As RegistryKey = Registry.ClassesRoot.CreateSubKey(".hexhash\shell\afirma.hexhash\command")
        hexHashCommand.SetValue("", args(0) + "\AutoFirma.exe checkdigest -i ""%1"" -gui")
        hexHashCommand.Close()
        Console.WriteLine("Registros instalados correctamente")
    End Sub
End Module
