/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ContentType_H_
#define	_ContentType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OBJECT_IDENTIFIER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ContentType */
typedef OBJECT_IDENTIFIER_t	 ContentType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContentType;
asn_struct_free_f ContentType_free;
asn_struct_print_f ContentType_print;
asn_constr_check_f ContentType_constraint;
ber_type_decoder_f ContentType_decode_ber;
der_type_encoder_f ContentType_encode_der;
xer_type_decoder_f ContentType_decode_xer;
xer_type_encoder_f ContentType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ContentType_H_ */
