/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SignerInfo_H_
#define	_SignerInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CMSVersion.h"
#include "SignerIdentifier.h"
#include "DigestAlgorithmIdentifier.h"
#include "SignatureAlgorithmIdentifier.h"
#include "SignatureValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignedAttributes;
struct UnsignedAttributes;

/* SignerInfo */
typedef struct SignerInfo {
	CMSVersion_t	 version;
	SignerIdentifier_t	 sid;
	DigestAlgorithmIdentifier_t	 digestAlgorithm;
	struct SignedAttributes	*signedAttrs	/* OPTIONAL */;
	SignatureAlgorithmIdentifier_t	 signatureAlgorithm;
	SignatureValue_t	 signature;
	struct UnsignedAttributes	*unsignedAttrs	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignerInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignerInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignedAttributes.h"
#include "UnsignedAttributes.h"

#endif	/* _SignerInfo_H_ */
