/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "SIGNEDDATA"
 * 	found in "SIGNEDDATA.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SigPolicyId_H_
#define	_SigPolicyId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OBJECT_IDENTIFIER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SigPolicyId */
typedef OBJECT_IDENTIFIER_t	 SigPolicyId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SigPolicyId;
asn_struct_free_f SigPolicyId_free;
asn_struct_print_f SigPolicyId_print;
asn_constr_check_f SigPolicyId_constraint;
ber_type_decoder_f SigPolicyId_decode_ber;
der_type_encoder_f SigPolicyId_encode_der;
xer_type_decoder_f SigPolicyId_decode_xer;
xer_type_encoder_f SigPolicyId_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SigPolicyId_H_ */
